//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DtabaseFirstApproach
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int AppointmentID { get; set; }
        public int DoctorID { get; set; }
        public int PID { get; set; }
        public Nullable<System.DateTime> AppointmentTime { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        //Turn off lazy loading for patient
        public Patient Patient { get; set; }
    }
}
